[package]
name = "redox-fatfs"
version = "0.1.0"
authors = ["Deepak Sirone <deepaksirone94@gmail.com>"]

[dependencies]
#spin = "0.4"
redox_syscall = "0.1"
uuid = { version = "0.5", features = ["v4"] }
byteorder = "1"
log = "0.4.6"
bitflags = "1.1.0"

[features]
default = ["secure"]
secure = []
